pipeline {
  agent any
  stages {
    stage('Git Clone') {
      steps {
          git credentialsId: 'github_auth', url: 'https://github.com/ArctiqTeam/e-containersecurity.git'
      }
    }
    stage ('Clean up local env'){
      steps {
        sh '''#!/bin/bash
        rm -rf /root/.ansible/*'''
      }
    }
    stage ('Run Playbook'){
      steps {
      ansiblePlaybook playbook: '${WORKSPACE}/modules/azure-origin-3.9/ansible/aqua-config.yml', sudoUser: null
      }
    }
    // stage ('Configure OSPF'){
    //   steps {
    //   ansiblePlaybook inventory: '${WORKSPACE}/ansible/inventory/jenkins/hosts', playbook: '${WORKSPACE}/ansible/configure.yml', sudoUser: null
    //   }
    // }


  }
}