pipeline {
  agent any
  stages {
    stage('Git Clone') {
      steps {
        notifyBuild('STARTED Policy Configuration')
          git credentialsId: 'github_auth', url: 'https://github.com/ArctiqTeam/e-containersecurity.git'
      }
    }
    stage ('Clean up local env'){
      steps {
        sh '''#!/bin/bash
        rm -rf /root/.ansible/*'''
      }
    }
    stage ('Run Playbook'){
      steps {
      ansiblePlaybook playbook: '${WORKSPACE}/modules/azure-origin-3.9/ansible/aqua-config.yml', sudoUser: null
      }
    }
    stage ('notify'){
      steps {
        notifyBuild('Finished Policy Configuration')

      }
    }


  }
}

def notifyBuild(String buildStatus = 'STARTED') {
  // build status of null means successful
  buildStatus =  buildStatus ?: 'SUCCESSFUL'

  // Default values
  def colorName = 'RED'
  def colorCode = '#FF0000'
  def subject = "${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
  def summary = "${subject} (${env.BUILD_URL})"

  // Override default values based on build status
  if (buildStatus == 'STARTED') {
    color = 'YELLOW'
    colorCode = '#FFFF00'
  } else if (buildStatus == 'SUCCESSFUL') {
    color = 'GREEN'
    colorCode = '#00FF00'
  } else {
    color = 'RED'
    colorCode = '#FF0000'
  }

  // Send notifications
  slackSend (color: colorCode, message: summary)
}
