pipeline {
  agent any
  stages {
    stage('Git Clone') {
      steps {
        sh '''
          #!/bin/bash
          git clone https://$CLIENT_ID@github.com/ArctiqTeam/e-containersecurity.git
          '''
          }
      }
    stage ('Clean up local env'){
      steps {
        sh '''#!/bin/bash
        rm -rf /root/.ansible/*'''
      }
    }
    // stage ('Test Connectivity'){
    //   steps {
    //   ansiblePlaybook inventory: '${WORKSPACE}/ansible/inventory/jenkins/hosts', playbook: '${WORKSPACE}/ansible/test.yml', sudoUser: null
    //   }
    // }
    // stage ('Configure OSPF'){
    //   steps {
    //   ansiblePlaybook inventory: '${WORKSPACE}/ansible/inventory/jenkins/hosts', playbook: '${WORKSPACE}/ansible/configure.yml', sudoUser: null
    //   }
    // }
   stage ('Build Complete'){
   steps{
   }
   }

  }
}