pipeline {
  node('nodejs')
  {
    stages {
      stage('Stage 1') {
        steps {
          sh "echo Stage 1"
        }
      }
      stage ('Stage 2'){
        steps {
          sh "echo Stage 1"
        }
      }
      stage ('Stage 3'){
        steps {
          sh "echo Stage 1"
        }
      }
      stage ('Wrap it up'){
        steps {
          sh "echo Stage 1"
        }

      }
    }
  }
}